version: "3"

vars:
  VERSION:
    sh: |
      tag="$(git describe --tags --exact-match 2>/dev/null || true)"
      if [ -n "${tag}" ]; then
        printf "%s" "${tag}"
      else
        printf "dev"
      fi
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || printf "unknown"
  DATE:
    sh: date -u +%Y-%m-%dT%H:%M:%SZ

tasks:
  build:
    desc: Build stable kra binary at ./kra
    cmds:
      - go build -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.DATE}}" -o kra ./cmd/kra

  build-exp:
    desc: Build experimental kra binary at ./kra
    cmds:
      - go build -tags experimental -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.DATE}}" -o kra ./cmd/kra

  run:
    desc: Run stable kra from source
    cmds:
      - go run ./cmd/kra {{.CLI_ARGS}}

  run-exp:
    desc: Run experimental kra from source
    cmds:
      - go run -tags experimental ./cmd/kra {{.CLI_ARGS}}

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test:race:
    desc: Run tests with race detector
    cmds:
      - go test -race ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  vuln:
    desc: Run govulncheck
    cmds:
      - go run golang.org/x/vuln/cmd/govulncheck@v1.1.4 ./...

  gosec:
    desc: Run gosec
    cmds:
      - go run github.com/securego/gosec/v2/cmd/gosec@v2.22.11 -exclude=G304 -- ./...

  fmt:
    desc: Format all Go files
    cmds:
      - gofmt -w $(gofmt -l .)

  check:
    desc: Run minimum quality gate
    cmds:
      - test -z "$(gofmt -l .)"
      - ./scripts/lint-ui-color.sh
      - go vet ./...
      - go test ./...

  ci:full:
    desc: Extended CI checks (race/vuln/security)
    cmds:
      - task: check
      - task: test:race
      - task: vuln
      - task: gosec

  release:preflight:
    desc: Run release preflight checks
    cmds:
      - task: check

  clean:
    desc: Remove built binary
    cmds:
      - rm -f kra
