version: "3"

tasks:
  build:
    desc: Build stable kra binary at ./kra
    cmds:
      - go build -o kra ./cmd/kra

  build-exp:
    desc: Build experimental kra binary at ./kra
    cmds:
      - go build -tags experimental -o kra ./cmd/kra-exp

  run:
    desc: Run stable kra from source
    cmds:
      - go run ./cmd/kra {{.CLI_ARGS}}

  run-exp:
    desc: Run experimental kra from source
    cmds:
      - go run -tags experimental ./cmd/kra-exp {{.CLI_ARGS}}

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  fmt:
    desc: Format all Go files
    cmds:
      - gofmt -w $(gofmt -l .)

  check:
    desc: Run minimum quality gate
    cmds:
      - test -z "$(gofmt -l .)"
      - ./scripts/lint-ui-color.sh
      - go vet ./...
      - go test ./...

  clean:
    desc: Remove built binary
    cmds:
      - rm -f kra
